apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    fabric8.io/git-branch: release-v2.2.311
    fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/jenkins/src/main/fabric8/icon.svg
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=jenkins&var-version=2.2.311
  creationTimestamp: 2018-04-28T06:22:15Z
  generation: 5
  labels:
    group: io.fabric8.devops.apps
    project: jenkins
    provider: fabric8
    version: 2.2.311
  name: jenkins
  namespace: fabric8
  resourceVersion: "12379435"
  selfLink: /apis/extensions/v1beta1/namespaces/fabric8/deployments/jenkins
  uid: 7e8244b1-4aac-11e8-bc69-005056074ff5
spec:
  replicas: 1
  selector:
    matchLabels:
      group: io.fabric8.devops.apps
      project: jenkins
      provider: fabric8
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        fabric8.io/git-branch: release-v2.2.311
        fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/jenkins/src/main/fabric8/icon.svg
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=jenkins&var-version=2.2.311
        fabric8.io/secret-docker-cfg: jenkins-docker-cfg
        fabric8.io/secret-gpg-key: jenkins-release-gpg
        fabric8.io/secret-hub-api-token: jenkins-hub-api-token
        fabric8.io/secret-maven-settings: jenkins-maven-settings
        fabric8.io/secret-ssh-config: jenkins-ssh-config
        fabric8.io/secret-ssh-key: jenkins-git-ssh,jenkins-master-ssh
      creationTimestamp: null
      labels:
        group: io.fabric8.devops.apps
        project: jenkins
        provider: fabric8
        version: 2.2.311
    spec:
      containers:
      - env:
        - name: PROJECT_VERSION
          valueFrom:
            configMapKeyRef:
              key: project-version
              name: jenkins
        - name: PIPELINE_ELASTICSEARCH_PROTOCOL
          valueFrom:
            configMapKeyRef:
              key: pipeline-elasticsearch-protocol
              name: jenkins
        - name: JENKINS_GOGS_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: jenkins-gogs-password
              name: jenkins
        - name: JENKINS_GOGS_USER
          valueFrom:
            configMapKeyRef:
              key: jenkins-gogs-user
              name: jenkins
        - name: JENKINS_GOGS_EMAIL
          valueFrom:
            configMapKeyRef:
              key: jenkins-gogs-email
              name: jenkins
        - name: PIPELINE_ELASTICSEARCH_HOST
          valueFrom:
            configMapKeyRef:
              key: pipeline-elasticsearch-host
              name: jenkins
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_MASTER
          value: https://kubernetes.default
        image: jenkins/jenkins
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /blue/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: jenkins
        ports:
        - containerPort: 50000
          name: slave
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /blue/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/jenkins_home/jobs
          name: jenkins-jobs
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - chmod
        - "777"
        - /var/jenkins_home/
        image: busybox
        imagePullPolicy: IfNotPresent
        name: init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home/
          name: jenkins-home
        - mountPath: /var/jenkins_home/jobs
          name: jenkins-jobs
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: jenkins
      serviceAccountName: jenkins
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jenkins-jobs
        persistentVolumeClaim:
          claimName: jenkins-jobs
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-workspace
status:
  conditions:
  - lastTransitionTime: 2018-04-28T06:22:15Z
    lastUpdateTime: 2018-04-28T06:22:15Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
